apiVersion: apps/v1
kind: Deployment
metadata:
  name: snippets-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: snippets-deployment
  template:
    metadata:
      labels:
        app: snippets-deployment
    spec:
      containers:
        - name: snippets-app
          image: europe-west4-docker.pkg.dev/williamscj-demos/snippets/snippets-image:v3
          #command: ["node", "index-db.js"]
          ports:
            - name: app-port
              containerPort: 4000
          env:
            - name: MYSQL_HOST
              #this is the mysql service discovery being called
              value: mysql-svc
            - name: MYSQL_USER
              value: root
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secrets
                  key: rootPassword
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: mysql-secrets
                  key: database